# Generated by Django 3.0.7 on 2020-06-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoogge', '0002_auto_20200618_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinNow',
            new_name='Subscribers',
        ),
    ]
