# Generated by Django 3.0.7 on 2020-06-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoogge', '0003_auto_20200625_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
