# Generated by Django 3.0.7 on 2020-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoogge', '0004_auto_20200625_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribe',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
